sudo: required
services: 
  - docker
  - neo4j
before_install:
  - docker build -t tundeker/docker_react -f Dockerfile.dev .

script: 
  - docker run tundeker/docker_react npm run test -- --coverage
