sudo: required
services: 
  - docker

before_install:
  - docker build -t tundeker/docker_react -f Dockerfile.dev .

scripts: 
  - docker run tundeker/docker_react npm run test -- --coverage --trace